forum_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import home
from accounts.views import login

urlpatterns = [
    url(r'^$', home, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),

    # add a new success url to the account login
    url(r'^accounts/login/$', login, { 'success_url': 'index' }, name='login'),
    # import the rest of the accounts urls after so the override is
    # processed first by the urls system
    url(r'^accounts/', include('accounts.urls')),
    url(r'^threads/', include('threads.urls')),
]

threads/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework import routers
from .views import threads, thread, edit_thread, new_thread, new_post, edit_post, delete_post, thread_vote
from rest_views import PollViewSet, PollInstanceView, VoteInstanceView, PostUpdateView, PostDeleteView

urlpatterns = [
    url(r'^threads/(?P<subject_id>\d+)/$', threads, name='threads'),
    url(r'^thread/(?P<thread_id>\d+)/$', thread, name='thread'),
    url(r'^thread/new/(?P<subject_id>\d+)/$', new_thread, name='new_thread'),
    url(r'^thread/edit/(?P<thread_id>\d+)/$', edit_thread, name='edit_thread'),
    url(r'^thread/vote/(?P<thread_id>\d+)/(?P<subject_id>\d+)/$', thread_vote, name='cast_vote'),
    url(r'^post/new/(?P<thread_id>\d+)/$', new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$', edit_post, name='edit_post'),
    url(r'^post/delete_post/(?P<post_id>\d+)/$', delete_post, name='delete_post'),
    url(r'^polls/$', PollViewSet.as_view()),
    url(r'^polls/(?P<pk>[\d]+)/$', PollInstanceView.as_view(), name='poll-instance'),
    url(r'^polls/vote/(?P<thread_id>[\d]+)/$', VoteInstanceView.as_view(), name='vote-instance'),
    url(r'^post/update/(?P<pk>[\d]+)/$', PostUpdateView.as_view(), name='update-poll'),
    url(r'^post/delete/(?P<pk>[\d]+)/$', PostDeleteView.as_view(), name='delete-poll'),
]

threads/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField

class Subject(models.Model):
    name = models.CharField(max_length=254)
    description = HTMLField()

    def __unicode__(self):
        return self.name

class Thread(models.Model):
    name = models.CharField(max_length=254)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads')
    subject = models.ForeignKey(Subject, related_name='threads')
    created_at = models.DateTimeField(default=timezone.now())

class Posts(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    created_at = models.DateTimeField(default=timezone.now())

class Poll(models.Model):
    question = models.TextField()
    thread = models.OneToOneField(Thread, null=True)
    
class PollSubject(models.Model):
    name = models.CharField(max_length=256)
    poll = models.ForeignKey(Poll, related_name='subjects')        
    
    
class Vote(models.Model):
    poll = models.ForeignKey(Poll, related_name="votes")
    subject = models.ForeignKey(PollSubject, related_name="votes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,  related_name="votes")
    

threads/forms.py
from django import forms
from django.forms.models import BaseModelFormSet
from threads.models import Thread, Posts, Poll, PollSubject


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)
    
    class Meta:
        model = Thread
        fields = ['name']
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['comment']
        
class PollForm(forms.ModelForm):
    question = forms.CharField(label="What is your poll about?")
    class Meta:
        model = Poll
        fields = ['question']
        
class PollSubjectForm(forms.ModelForm):
    name = forms.CharField(label="Poll subject name", required=True)
    
    def __init__(self, *args, **kwargs):
        super(PollSubjectForm, self).__init__(*args, **kwargs)
        
        self.empty_permitted = False
        
    class Meta:
        model = PollSubject
        fields = ['name']    

threads/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from threads.forms import ThreadForm, PostForm, PollForm, PollSubjectForm

from django.forms.formsets import formset_factory
from threads.models import Thread, Posts, Subject, Poll, PollSubject
from django.contrib import messages

def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'threads.html', { 'subject': subject })

def thread(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    args = { 'thread': thread }    
    args.update(csrf(request))
    return render(request, 'thread.html', args)

@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    PollSubjectFormset = formset_factory(PollSubjectForm,  extra=3)
    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = PollSubjectFormset(request.POST)
        
        result = poll_subject_formset.is_valid()
        
        if request.POST.get('is_a_poll', None):
            if thread_form.is_valid() and post_form.is_valid() \
                and poll_form.is_valid() and poll_subject_formset.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()
    
                post = post_form.save(False)
                post.user = request.user
                post.thread = thread
                post.save() 
                
                poll = poll_form.save(False)
                poll.thread = thread
                poll.save()
                
                for subject_form in poll_subject_formset:
                    subject = subject_form.save(False)
                    subject.poll = poll
                    subject.save()
                    
                messages.success(request, "Your have create a new thread!")
                
                return redirect(reverse('thread', args={thread.pk}))                
                    
        else:
        
            if thread_form.is_valid() and post_form.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()
    
                post = post_form.save(False)
                post.user = request.user
                post.thread = thread
                post.save()
                
                messages.success(request, "Your have create a new thread!")
                
                return redirect(reverse('thread', args={thread.pk}))                
     
    else:
        thread_form = ThreadForm()
        post_form = PostForm()
        poll_form = PollForm()
        poll_subject_formset = PollSubjectFormset()

    args = {
        'thread_form' : thread_form,
        'post_form' : post_form,
        'subject' : subject,
        'poll_form' : poll_form,
        'poll_subject_formset' : poll_subject_formset,
    }
    args.update(csrf(request))

    return render(request, 'thread_form.html', args)

@login_required
def edit_thread(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = ThreadForm(request.POST, instance=thread)
        if form.is_valid():
            thread = form.save()
            messages.success(request, "Your have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = ThreadForm(instance=thread)

    args = { 'form' : form }
    args.update(csrf(request))

    return render(request, 'thread_form.html', args)

@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form' : form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'post_form.html', args)

@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Posts, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, "Your have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)


    args = {
        'form' : form,
        'form_action': reverse('edit_post',  kwargs={"thread_id" : thread.id, "post_id": post.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'post_form.html', args)

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))

@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)
    
    subject = thread.poll.votes.filter(user=request.user) 
    
    if subject:
        messages.error(request, "You already voted on this! ... your not trying to cheat are you?")
        return redirect(reverse('thread', args={thread_id}))
    
    subject = PollSubject.objects.get(id=subject_id)
    
    subject.votes.create(poll=subject.poll, user=request.user)
    
    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))

threads/templates/comment_details.html
{% load thread_extras %}
<div class="details">
    <div class="col-md-6">
        <div class="pull-left">
            <time datetime="{{ post.created_at }}">
              Posted: {{ post.created_at|started_time }}
            </time>
        </div>
    </div>
    <div class="col-md-6">
        <div class="pull-right">
          {% if post.user == user or user.is_staff %}
            <a href="{% url 'edit_post' thread.id post.id %}"><i class="fa fa-pencil-square-o"></i></a>
            <a href="{% url 'delete_post' post.id %}"><i class="fa fa-trash-o"></i></a>
          {% endif %}
        </div>
    </div>
    <div class="clearfix"></div>
</div>

threads/templates/poll.html
<div class="container" ng-app="pollApp">
    <div class="col-md-6">
      <div class="panel panel-default" ng-controller="PollCtrl">
          <div class="panel-heading"><strong>Poll - {$ poll.question $} (Total of {$ poll.total_votes $} votes so far)</strong></div>
          <div class="panel-body">
          <p>Heres how the votes are so far:</p>
          <div ng-repeat="subject in poll.subjects">
              <div class="col-md-9">
                <strong>{$ subject.name $}</strong>
                <span class="pull-right">{$ subject.percentage_of_votes $}%</span>
              </div>
            
              <span ng-if="poll.user_has_voted == false" ng-click='vote(poll, subject)' class="glyphicon glyphicon-ok col-md-3 btn-vote"></span>
            
              <div class="col-md-9">            
                <div class="progress">
                  <div class="progress-bar progress-bar-info"
                          role="progressbar" aria-value="{$ subject.percentage_of_votes $}"
                          aria-valuemin="0" aria-valuemax="100" 
                          style="width:{$ subject.percentage_of_votes $}%;">
                  </div>
                </div>
              </div> 
            </div> <!-- end ng-repeat -->
          </div>
        </div>
    </div> 
  </div>

threads/templates/post.html
{% load staticfiles %}
{% load emoticons_tags %}
<section class="row comment col-md-9">
  <div class="col-md-3 comment-profile">
    <p><img src="{% static 'images/user.png' %}" /></p>
    <p>{{ post.user.username }}</p>
    <p>{{ post.user.posts.count }} POSTS</p>
  </div>
  <div class="col-md-9 ">
    <div class="comment-content">
      {% autoescape off %}
        {{ post.comment|emoticons }}
      {% endautoescape %}
    </div>
    {% include "comment_details.html" %}
  </div>
  
</section>

threads/templates/post_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load staticfiles %}
{% block head_js %}
<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript">
  tinyMCE.init({
    mode: "textareas",
    theme: "modern",
    plugins: "paste",
});
</script>
{% endblock %}
{% block content %}
  <section>
    <div class="col-md-9">
      <form method="post" action="{{ form_action }}">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">{{button_text}}</button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

threads/templates/thread.html
{% extends "base.html" %}
{% load thread_extras %}
{% load staticfiles %}
{% block head_js %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.min.js"></script>
{% endblock %}

{% block footer_js %}
<script type="text/javascript">
  /*   
    define our poll id for use with AngularJS 
  */
  var pollID = {{thread.poll.id}};
</script>
<script src="{% static "js/apps/pollsApp.js" %}"></script>
{% endblock %}
{% block content %}
  
  <div class="row header">
    
    <div class="container">
      <h2>{{ thread.name }}</h2>
      <div class="col-md-12">
          <table class="table">
              <tbody>
              <tr>
                  <th>
                    CREATED
                  </th>
                  <th>OWNER</th>
                  <th>LAST POST</th>
              </tr>
              <tr>
                  <td>
                    <time datetime="{{ thread.created_at }}">
                      {{ thread.created_at|started_time }}
                    </time>
                  </td>
                  <td>{{ thread.user.username }}</td>
                  <td>{% last_posted_user_name thread %}</td>
              </tr>
            </tbody>
          </table>
      </div>
      {% if thread.poll %}
        {% csrf_token %}
        {% include 'poll.html' %}
      {% endif %}
    
      {% if user.is_authenticated %}
        <p>
          <a href="{% url 'new_post' thread.id %}" class="btn btn-primary">New post</a>
        </p>
      {% endif %}
    </div>
  </div>
  <div class="container">
    {% for post in thread.posts.all %}
      {% include "post.html" %}
    {% endfor %}
  </div>
{% endblock %}

threads/templates/thread_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load staticfiles %}
{% block head_js %}
<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript">
  tinyMCE.init({
    mode: "textareas",
    theme: "modern",
    plugins: "paste",
});
</script>
{% endblock %}
{% block content %}
  <section>
    <div class="col-md-9">
      <form method="post" action="{% url 'new_thread' subject.id %}">
        {% csrf_token %}
        <div class="form-group">
        {{ thread_form|bootstrap }}
        {{ post_form|bootstrap }}
        </div>
        <div id="poll_form" class="form-group">
        {{ poll_form|bootstrap }}
        {{ poll_subject_formset.management_form }}
        {% for poll_subject_form in poll_subject_formset %}
            {{ poll_subject_form|bootstrap }}
        {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Post new thread</button>
        </div>
      </form>
    </div>
  </section>
  <script type="text/javascript">
    $(function() {
      if(!$('#id_is_a_poll').is(':checked')) {
        $('#poll_form').hide();
      }
      
      $('#id_is_a_poll').click(function(el) {
        var poll_form = $('#poll_form');
        
        if(poll_form.is(":visible")) {
          poll_form.hide();
        } else {
          poll_form.show();
        }
      });
    });
  </script>
{% endblock %}

threads/templates/thread_item.html
<section class="thread">
  <header>
    <table>
      <tr>
        <td>
          <a href="{% url 'thread' thread.id %}"><h4>{{ thread.name }}</h4></a>
        </td>
      </tr>
    </table>

  </header>
</section>

threads/templates/threads.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
  <div class="row header">
    <div class="jumbotron"><h1>{{ subject.name }}</h1></div>
  </div>
  <div class="col-md-12">
    {% if user.is_authenticated %}
      <p>
        <a href="{% url 'new_thread' subject.id %}" class="btn btn-primary">New Thread</a>
      </p>
    {% endif %}
    {% for thread in subject.threads.all %}
      {% include "thread_item.html" %}
    {% endfor %}
  </div>
{% endblock %}